name: Attendance Trigger Bot

on:
  schedule:
    # Mon–Fri only (UTC time converted from PH +8)
    - cron: "0 23 * * 0-4"   # 7:00 AM PH → markremainingAsAbsent
    - cron: "0 0 * * 1-5"    # 8:00 AM PH → sendStyledSummary
    - cron: "0 1 * * 1-5"    # 9:00 AM PH → emailattendanceReport
    - cron: "0 8 * * 1-5"    # 4:00 PM PH → BackupAt4PM
    - cron: "0 15 * * 1-5"   # 11:00 PM PH → resetSheet2Log, resetLogAtMidnight

  workflow_dispatch: # manual run button

jobs:
  run-triggers:
    runs-on: ubuntu-latest
    steps:
      - name: Call Apps Script - markremainingAsAbsent
        if: github.event.schedule == '0 23 * * 0-4'
        run: |
          curl -L -X POST "https://script.google.com/macros/s/AKfycbyv9vi47VEP2xY2TOVONf8OdGk_Cy4otSjJBsq5xGMCGFz1B2uk3qzG9JY6e_F5NK5M/exec?trigger=markremainingAsAbsent"

      - name: Call Apps Script - sendStyledSummary
        if: github.event.schedule == '0 0 * * 1-5'
        run: |
          curl -L -X POST "https://script.google.com/macros/s/AKfycbyv9vi47VEP2xY2TOVONf8OdGk_Cy4otSjJBsq5xGMCGFz1B2uk3qzG9JY6e_F5NK5M/exec?trigger=sendStyledSummary"

      - name: Call Apps Script - emailattendanceReport
        if: github.event.schedule == '0 1 * * 1-5'
        run: |
          curl -L -X POST "https://script.google.com/macros/s/AKfycbyv9vi47VEP2xY2TOVONf8OdGk_Cy4otSjJBsq5xGMCGFz1B2uk3qzG9JY6e_F5NK5M/exec?trigger=emailattendanceReport"

      - name: Call Apps Script - BackupAt4PM
        if: github.event.schedule == '0 8 * * 1-5'
        run: |
          curl -L -X POST "https://script.google.com/macros/s/AKfycbyv9vi47VEP2xY2TOVONf8OdGk_Cy4otSjJBsq5xGMCGFz1B2uk3qzG9JY6e_F5NK5M/exec?trigger=BackupAt4PM"

      - name: Call Apps Script - resetSheet2Log
        if: github.event.schedule == '0 15 * * 1-5'
        run: |
          curl -L -X POST "https://script.google.com/macros/s/AKfycbyv9vi47VEP2xY2TOVONf8OdGk_Cy4otSjJBsq5xGMCGFz1B2uk3qzG9JY6e_F5NK5M/exec?trigger=resetSheet2Log"

      - name: Call Apps Script - resetLogAtMidnight
        if: github.event.schedule == '0 15 * * 1-5'
        run: |
          curl -L -X POST "https://script.google.com/macros/s/AKfycbyv9vi47VEP2xY2TOVONf8OdGk_Cy4otSjJBsq5xGMCGFz1B2uk3qzG9JY6e_F5NK5M/exec?trigger=resetLogAtMidnight"
