name: Attendance Report Bot


on:
  schedule:
    # Mon–Fri at 8:00 AM PH Time (00:00 UTC)
    - cron: '0 0 * * 1-5'
  workflow_dispatch:
 
jobs:
  trigger-apps-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check if today is Mon–Fri
        run: |
          DAY=$(date +%u)  # 1 = Monday, 7 = Sunday
          if [ $DAY -gt 5 ]; then
            echo "Today is Saturday or Sunday. Skipping..."
            exit 0
          fi
      - name: Trigger Google Apps Script for Both Reports
        run: |
          curl -X GET "https://script.google.com/macros/s/AKfycbwHPCfx2XbVgOpUcQUsgnKbVULu6VNLB5xzho8YPGK3c4lJynSQpKh6B3rgS64kWRnj/exec"
