name: Attendance Bot

on:
  schedule:
    # PH time converted to UTC (PH -8)
    - cron: "23 23 * * 0-4"   # 7:00 AM PH (markremainingAsAbsent)
    - cron: "0 0 * * 1-5"     # 8:00 AM PH (sendStyledSummary)
    - cron: "1 0 * * 1-5"     # 8:01 AM PH (emailAttendanceReport)
    - cron: "8 8 * * 1-5"     # 4:00 PM PH (BackupAt4PM)
    - cron: "15 15 * * 1-5"   # 11:00 PM PH (resetSheet2Log)
    - cron: "15 16 * * 1-5"   # 12:00 Midnight PH (resetLogAtMidnight)
  workflow_dispatch:

jobs:
  run-triggers:
    runs-on: ubuntu-latest
    steps:
      - name: Call sendStyledSummary
        run: |
          curl -L "https://script.google.com/macros/s/AKfycbwSGQZEOmEf-w7yUsc1NrhdLzFArLfdbGxz77lcR7FDCCJ01tVUqNW3PhBBQhaFE2Cy/exec?action=sendStyledSummary"
      - name: Call emailAttendanceReport
        run: |
          curl -L "https://script.google.com/macros/s/AKfycbwSGQZEOmEf-w7yUsc1NrhdLzFArLfdbGxz77lcR7FDCCJ01tVUqNW3PhBBQhaFE2Cy/exec?action=emailAttendanceReport"
      - name: Call BackupAt4PM
        run: |
          curl -L "https://script.google.com/macros/s/AKfycbwSGQZEOmEf-w7yUsc1NrhdLzFArLfdbGxz77lcR7FDCCJ01tVUqNW3PhBBQhaFE2Cy/exec?action=BackupAt4PM"
      - name: Call resetSheet2Log
        run: |
          curl -L "https://script.google.com/macros/s/AKfycbwSGQZEOmEf-w7yUsc1NrhdLzFArLfdbGxz77lcR7FDCCJ01tVUqNW3PhBBQhaFE2Cy/exec?action=resetSheet2Log"
      - name: Call markremainingAsAbsent
        run: |
          curl -L "https://script.google.com/macros/s/AKfycbwSGQZEOmEf-w7yUsc1NrhdLzFArLfdbGxz77lcR7FDCCJ01tVUqNW3PhBBQhaFE2Cy/exec?action=markremainingAsAbsent"
      - name: Call resetLogAtMidnight
        run: |
          curl -L "https://script.google.com/macros/s/AKfycbwSGQZEOmEf-w7yUsc1NrhdLzFArLfdbGxz77lcR7FDCCJ01tVUqNW3PhBBQhaFE2Cy/exec?action=resetLogAtMidnight"
