name: Trigger Google Script Backup

on:
  schedule:
    - cron: "0 23 * * 0-4" # 7 AM PH = 11 PM UTC, Mon-Fri

jobs:
  run-backup:
    runs-on: ubuntu-latest
    steps:
      - name: Call Google Apps Script Backup
        run: |
          curl -L -X GET "https://script.google.com/macros/s/AKfycbyv9vi47VEP2xY2TOVONf8OdGk_Cy4otSjJBsq5xGMCGFz1B2uk3qzG9JY6e_F5NK5M/exec"
